sudo: false
language: python
python:
  - "2.7"
  # Coverage doesn't support Python 3.2
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install coverage coveralls flake8
script:
  - flake8 humanhash.py
  - coverage run humanhash.py
after_script:
  - coverage report
  - coverage combine
  - coveralls
